### PR TITLE
Add lowercase and uppercase helpers

### PR DESCRIPTION
**Pull request by Moxide**
See #5 
Implements lowercase and uppercase helpers...

### CODE REVIEW

**Comment by romulomachado** [comment]
Hey, @Moxide, thanks sending the PR! 

This looks pretty good, but could you also create integration tests (`tests/integration/helpers/uppercase-test.js` and `tests/integration/helpers/lowercase-test.js`) for those new helpers?

**Comment by Moxide** [comment]
Hello, 
sorry, forgot those ;-)
Done...

**Comment by romulomachado** [comment]
Awesome, @Moxide!

**Comment by Moxide** [comment]
You're welcome ;-)

**Pull request merged**
