### PR TITLE
Embroider

### LINKED ISSUE #308: Compatibility with Embroider
I'm not sure if there's much to do here besides some documentation around Embroider but thought I'd raise it anyway.

### Problem

It appears things are stabilising around Embroider because since ember-cli 3.25.0 [all newly-created addons will have Embroider testing baked into ember-try](https://github.com/ember-cli/ember-cli/pull/9436) by default. I've been experimenting with Embroider and various addons and it appears that `ember-cli-string-helpers` is incompatible with an Embroider app when you use the `only` or `except` configuration.

If you try and run a build using the following configuration it fails with the 

```js
'ember-cli-string-helpers': {
  only: ['dasherize', 'underscore'],
  except: ['titleize', 'capitalize'],
},
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: ModuleNotFoundError: Module not found: Error: Can't resolve '../node_modules/ember-cli-string-helpers/helpers/capitalize' in '$TMPDIR/embroider/f661dd/helpers'
    at /Users/pat/hacking/string-helpers-embroider/node_modules/webpack/lib/Compilation.js:925:10
    at /Users/pat/hacking/string-helpers-embroider/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/pat/hacking/string-helpers-embroider/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/pat/hacking/string-helpers-embroider/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/pat/hacking/string-helpers-embroider/node_modules/neo-async/async.js:2830:7
    at /Users/pat/hacking/string-helpers-embroider/node_modules/neo-async/async.js:6877:13
    at /Users/pat/hacking/string-helpers-embroider/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/pat/hacking/string-helpers-embroider/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /Users/pat/hacking/string-helpers-embroider/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/Users/pat/hacking/string-helpers-embroider/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

I have a reproduction in this repo [here](https://github.com/patocallaghan/string-helpers-embroider). You can see the configuration used in https://github.com/patocallaghan/string-helpers-embroider/commit/39003b207455995d48f3d65a31239e0c77b4f33a

### Embroider support
It's worth calling out that the use case for using the `only` and `except` configuration will no longer be required by Embroider "Optimized" mode, i.e. tree-shaking enabled, as that will only load the helpers in your build that you specifically use.

I guess the problem with this addon is if folks are using Embroider "Safe" mode which aims to offer full backwards compatibility with the existing Ember CLI pipeline.

### Fix?
I'm not sure if it's worth fixing this as personally I'm just going to remove the `only` and `except` config while we are experimenting with Embroider "Safe" mode. Maybe all that is required is some documentation on Embroider compatibility in the README. With Embroider "Optimized" mode the use case for `only` and `except` is no longer needed.

### PR DESCRIPTION
**Pull request by ctjhoa**
Closes #308 & #294.

## Changes proposed in this pull request
- Add Embroider support & CI tests

### CODE REVIEW

**Comment by ctjhoa** [comment]
https://github.com/embroider-build/embroider/tree/master/packages/test-setup
For more information

**Comment by ctjhoa** [comment]
@romulomachado up

**Comment by romulomachado** [comment]
@ctjhoa Thanks for the PR! I've been behind the updates on this repo for a long time, looking to catch up now!

**Comment by romulomachado** [comment]
This is available on `6.0.1` :tada:

**Comment by ndekeister-us** [comment]
@romulomachado would be awesome if you could update `Latest release` (+ add a description of changes) The fact that this PR also fix the whitelist/blacklist feature is really interesting 🎉 (Thanks for this fix)

**Pull request merged**
