### PR TITLE
Updated to ember-cli 2.16.2

### PR DESCRIPTION
**Pull request by tzellman**
## Changes proposed in this pull request

This change updates the included ember-cli dependency of the addon to the latest LTS (2.16).

The primary changes were to the versions updated when running `ember init` as well as updates to use the [ember modules API](https://emberjs.com/blog/2017/10/11/ember-2-16-released.html#toc_ember-js-modules-api).

Thanks!

### CODE REVIEW

**Comment by GavinJoyce** [comment]
👍 came here to make the same PR. 

As we're approaching Ember 3.0, and people are likely preparing their apps by removing deprecating warnings, it would be good to merge this so that they don't have to dig into the source of these particular warnings.

@romulomachado perhaps you might release a new version once this has merged? Thanks

**Comment by romulomachado** [comment]
@tzellman @GavinJoyce Sorry, I missed this PR.

I'm reviewing (and hopefully merging) it later today.

**Comment by GavinJoyce** [comment]
Great, thanks @romulomachado!

**Comment by romulomachado** [comment]
@tzellman Thank you for the PR! 



@GavinJoyce [1.6.0](https://www.npmjs.com/package/ember-cli-string-helpers) is now available on NPM.

**Comment by GavinJoyce** [comment]
Thanks!

**Pull request merged**
