### PR TITLE
Gracefully Handle Empty Args to `{{w`

### LINKED ISSUE #3: `w` Helper is Throwing in Ember 2.12
## Version

In Ember 2.12, in two different applications, the following error is thrown by the `w` helper:

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at w (w.js:11)
    at ember.debug.js:15526
    at Function.create (ember.debug.js:15545)
    at v (ember.debug.js:9492)
```

The funny thing here is that we're not using this helper at all.

## Test Case

TBD. Apologies for now having this yet.

## Steps to reproduce

I haven't dug in too deeply, but as far as I can figure I simply have to install the addon.

## Expected Behavior

It doesn't throw.

## Actual Behavior

Throws, and I weep all over my keyboard.

### PR DESCRIPTION
**Pull request by jherdman**
This also fixes the integration test suite name

Resolves #3

### CODE REVIEW

**Comment by romulomachado** [comment]
This is awesome! Thanks for finding the bug, reporting and sending the PR.

**Comment by jherdman** [comment]
No worries! Would you be amenable to cutting a patch release with this change?

**Comment by romulomachado** [comment]
@jherdman Sorry, I forgot to do that. `1.0.1` can be downloaded from npm now. :wink:

**Comment by jherdman** [comment]
❤️

**Pull request merged**
